# SPDX-FileCopyrightText: © 2024 Jimmy Fitzpatrick <jcfitzpatrick12@gmail.com>
# This file is part of SPECTRE
# SPDX-License-Identifier: GPL-3.0-or-later

from abc import abstractmethod

from spectre.file_handlers.chunks.BaseChunk import BaseChunk
from spectre.spectrogram.Spectrogram import Spectrogram
from spectre.file_handlers.json.CaptureConfigHandler import CaptureConfigHandler

class SPECTREChunk(BaseChunk):
    def __init__(self, chunk_start_time: str, tag: str, **kwargs):
        super().__init__(chunk_start_time, tag, **kwargs)
        # each SPECTRE chunk will have an associated capture config (as it was generated by the program)
        capture_config_handler = CaptureConfigHandler(tag)
        self.capture_config = capture_config_handler.read()

    # additionally, we should be able to create a spectrogram based on the raw data
    @abstractmethod
    def build_spectrogram(self) -> Spectrogram:
        pass
