services:
  spectre-server:
    container_name: spectre-server
    image: spectregrams/spectre-server:5.2.1  # x-release-please-version
    environment:
      - SPECTRE_GID=${SPECTRE_GID}
      - SPECTRE_BIND_HOST=${SPECTRE_BIND_HOST}
      - SPECTRE_BIND_PORT=${SPECTRE_BIND_PORT}
    group_add:
      - "${SPECTRE_GID}"
    networks:
      - spectre-network
    volumes:
      - spectre-data-v5:/app/.spectre-data
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - "c 189:* rw"
    ports:
      - ${SPECTRE_PORT_MAP}
    stop_signal: SIGKILL

  spectre-cli:
    container_name: spectre-cli
    image: spectregrams/spectre-cli:5.2.1  # x-release-please-version
    environment:
      - SPECTRE_SERVER_HOST=${SPECTRE_SERVER_HOST}
      - SPECTRE_SERVER_PORT=${SPECTRE_SERVER_PORT}
    networks:
      - spectre-network
    depends_on:
      - spectre-server
    tty: true
    stop_signal: SIGKILL

networks:
  spectre-network:
    name: spectre-network
    driver: bridge

volumes:
  spectre-data-v5:
    name: spectre-data-v5
