# SPDX-FileCopyrightText: © 2024 Jimmy Fitzpatrick <jcfitzpatrick12@gmail.com>
# This file is part of SPECTRE
# SPDX-License-Identifier: GPL-3.0-or-later

from abc import ABC, abstractmethod

from spectre.chunks.BaseChunk import BaseChunk
from spectre.spectrogram.Spectrogram import Spectrogram
from spectre.json_config.CaptureConfigHandler import CaptureConfigHandler

# SPECTREChunk's are those generated by the program. So, they will:
# -> have an associated capture config
# -> can build a spectrogram based on raw data
class SPECTREChunk(ABC, BaseChunk):
    def __init__(self, chunk_start_time: str, tag: str):
        super().__init__(chunk_start_time, tag)
        
        capture_config_handler = CaptureConfigHandler(tag)
        self.capture_config = capture_config_handler.load_as_dict()
    
    
    # Abstract method to accomodate multiple types of data collection
    # -> fixed
    # -> sweeping
    # etc.
    @abstractmethod
    def build_spectrogram(self) -> Spectrogram:
        pass