# SPDX-FileCopyrightText: © 2024 Jimmy Fitzpatrick <jcfitzpatrick12@gmail.com>
# This file is part of SPECTRE
# SPDX-License-Identifier: GPL-3.0-or-later

import logging

from typing import Callable

class ChunkNotFoundError(Exception): ...
class ChunkFileNotFoundError(FileNotFoundError): ...
class InvalidMetadataError(Exception): ...
class InvalidSweepMetadataError(InvalidMetadataError): ...
class InvalidTagError(ValueError): ...
class SpectrogramNotFoundError(FileNotFoundError): ...
class LogNotFoundError(FileNotFoundError): ...
class ReceiverNotFoundError(Exception): ...
class InvalidReceiver(Exception): ...
class InvalidModeError(Exception): ...

